# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

before_install:
  - pip install poetry

install: make install-dev

# Command to run tests, e.g. python setup.py test
script: make test

after_success:
  - poetry run codecov


# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: piccolbo
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: piccolbo/altair_recipes
#     python: 3.6
